  #spring.application.name=NihonStudyGuide

  server:
    port: 8088
    servlet:
      context-path: /fja-fap

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: hoangson00as@gmail.com
      password: dyyiimysveqeooyt
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

  signer:
    key: owyceV4tzWzKJ2zMWYJkg2fV4QcPjHJlYt3QRfLoBsRuB6G6BRkURMevCbCEC7mb